version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/specifications/dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
